// Generated by CoffeeScript 1.6.3
(function() {
  var AuthenticateRequest;

  AuthenticateRequest = (function() {
    function AuthenticateRequest() {}

    AuthenticateRequest.prototype.authenticate = function(request, response, next) {
      if (request.user || request.path === '/login' || request.path === '/registration') {
        return next();
      } else {
        return response.redirect('/login');
      }
    };

    return AuthenticateRequest;

  })();

  module.exports = AuthenticateRequest;

}).call(this);
