// Generated by CoffeeScript 1.6.3
(function() {
  var EncryptionUtils, crypto;

  crypto = require('crypto');

  EncryptionUtils = (function() {
    function EncryptionUtils() {}

    EncryptionUtils.prototype.encrypt = function(plainText) {
      var cipher, cipherText;
      cipher = crypto.createCipher('aes-128-cbc', 'mary had a little lamb');
      cipherText = cipher.update(plainText, 'utf8', 'hex');
      return cipherText += cipher.final('hex');
    };

    return EncryptionUtils;

  })();

  module.exports = new EncryptionUtils;

}).call(this);
