// Generated by CoffeeScript 1.6.3
(function() {
  var LoginValidation, encryptionUtils, users;

  users = require('../db/users');

  encryptionUtils = require('./encryption_utils');

  LoginValidation = (function() {
    function LoginValidation() {}

    LoginValidation.prototype.validate_login = function(username, password, done) {
      var encryptedPassword;
      encryptedPassword = encryptionUtils.encrypt(password);
      return users.findUserByCredentials(username, encryptedPassword, function(results) {
        if (results.length > 0) {
          return done(null, results[0]);
        } else {
          return done(null, false, {
            message: 'Unauthenticated user'
          });
        }
      });
    };

    return LoginValidation;

  })();

  module.exports = new LoginValidation;

}).call(this);
