// Generated by CoffeeScript 1.6.3
(function() {
  var UserSerialization;

  UserSerialization = (function() {
    function UserSerialization() {}

    UserSerialization.prototype.serialize = function(user, done) {
      return done(null, user);
    };

    UserSerialization.prototype.deserialize = function(user, done) {
      return done(null, user);
    };

    return UserSerialization;

  })();

  module.exports = new UserSerialization;

}).call(this);
