// Generated by CoffeeScript 1.6.3
(function() {
  var CallbackGenerator;

  CallbackGenerator = (function() {
    function CallbackGenerator() {}

    CallbackGenerator.prototype.generateCallback = function(request, response) {
      var callback;
      callback = function(authError, user, info) {
        if (authError || !user) {
          console.log('authentication error: ' + authError);
          return response.redirect('/login?bad_login=true');
        }
        return request.login(user, function(loginError) {
          if (loginError) {
            console.log('login error: ' + loginError);
            return response.redirect('/login?bad_login=true');
          }
          return response.redirect('/');
        });
      };
      return callback;
    };

    return CallbackGenerator;

  })();

  module.exports = new CallbackGenerator;

}).call(this);
