// Generated by CoffeeScript 1.6.3
(function() {
  var Login, callbackGenerator, passport;

  passport = require('passport');

  callbackGenerator = require('./callback_generator.js');

  Login = (function() {
    function Login() {}

    Login.prototype.form = function(request, response) {
      var data;
      data = {
        bad_login: request.query.bad_login,
        created_user_successfully: request.query.created_user_successfully
      };
      return response.render('form', data);
    };

    Login.prototype.submit = function(request, response, next) {
      var auth, callback;
      callback = callbackGenerator.generateCallback(request, response);
      auth = passport.authenticate('local', callback);
      return auth(request, response, next);
    };

    return Login;

  })();

  module.exports = new Login;

}).call(this);
